const Movies2 = [
  {
    id: 1,
    Title: "Avatar",
    Year: "2009",
    Rated: "PG-13",
    Released: "18 Dec 2009",
    Runtime: "162 min",
    Genre: "Action, Adventure, Fantasy",
    Director: "James Cameron",
    Writer: "James Cameron",
    Actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
    Plot: "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    Language: "English, Spanish",
    Country: "USA, UK",
    Awards: "Won 3 Oscars. Another 80 wins & 121 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg",
    Metascore: "83",
    imdbRating: "7.9",
    imdbVotes: "890,617",
    imdbID: "tt0499549",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNzM2MDk3MTcyMV5BMl5BanBnXkFtZTcwNjg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxOTEwNDcxN15BMl5BanBnXkFtZTcwOTg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYxMDg1Nzk1MV5BMl5BanBnXkFtZTcwMDk0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    id: 2,
    Title: "I Am Legend",
    Year: "2007",
    Rated: "PG-13",
    Released: "14 Dec 2007",
    Runtime: "101 min",
    Genre: "Drama, Horror, Sci-Fi",
    Director: "Francis Lawrence",
    Writer:
      "Mark Protosevich (screenplay), Akiva Goldsman (screenplay), Richard Matheson (novel), John William Corrington, Joyce Hooper Corrington",
    Actors:
      "Will Smith, Alice Braga, Charlie Tahan, Salli Richardson-Whitfield",
    Plot: "Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.",
    Language: "English",
    Country: "USA",
    Awards: "9 wins & 21 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/iPDkaSdKk2jRLTM65UOEoKtsIZ8.jpg",
    Metascore: "65",
    imdbRating: "7.2",
    imdbVotes: "533,874",
    imdbID: "tt0480249",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI0NTI4NjE3NV5BMl5BanBnXkFtZTYwMDA0Nzc4._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTIwMDg2MDU4M15BMl5BanBnXkFtZTYwMTA0Nzc4._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MDM1OTU5OV5BMl5BanBnXkFtZTYwMjA0Nzc4._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0MTI2NjMzMzFeQTJeQWpwZ15BbWU2MDMwNDc3OA@@._V1_.jpg",
    ],
  },
  {
    id: 3,
    Title: "300",
    Year: "2006",
    Rated: "R",
    Released: "09 Mar 2007",
    Runtime: "117 min",
    Genre: "Action, Drama, Fantasy",
    Director: "Zack Snyder",
    Writer:
      "Zack Snyder (screenplay), Kurt Johnstad (screenplay), Michael Gordon (screenplay), Frank Miller (graphic novel), Lynn Varley (graphic novel)",
    Actors: "Gerard Butler, Lena Headey, Dominic West, David Wenham",
    Plot: "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
    Language: "English",
    Country: "USA",
    Awards: "16 wins & 42 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/9W49fy5G7v9Ed3CXtvMi41YqZtt.jpg",
    Metascore: "52",
    imdbRating: "7.7",
    imdbVotes: "611,046",
    imdbID: "tt0416449",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMwNTg5MzMwMV5BMl5BanBnXkFtZTcwMzA2NTIyMw@@._V1_SX1777_CR0,0,1777,937_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwNTgyNTMzNF5BMl5BanBnXkFtZTcwNDA2NTIyMw@@._V1_SX1777_CR0,0,1777,935_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0MjQzOTEwMV5BMl5BanBnXkFtZTcwMzE2NTIyMw@@._V1_SX1777_CR0,0,1777,947_AL_.jpg",
    ],
  },
  {
    id: 4,
    Title: "The Avengers",
    Year: "2012",
    Rated: "PG-13",
    Released: "04 May 2012",
    Runtime: "143 min",
    Genre: "Action, Sci-Fi, Thriller",
    Director: "Joss Whedon",
    Writer: "Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)",
    Actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
    Plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
    Language: "English, Russian",
    Country: "USA",
    Awards: "Nominated for 1 Oscar. Another 34 wins & 75 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    Metascore: "69",
    imdbRating: "8.1",
    imdbVotes: "1,003,301",
    imdbID: "tt0848228",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0NjY0NzE4OTReQTJeQWpwZ15BbWU3MDczODg2Nzc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE1MzEzMjcyM15BMl5BanBnXkFtZTcwNDM4ODY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwMzM2MTg1M15BMl5BanBnXkFtZTcwNjM4ODY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4NzM2Mjc5MV5BMl5BanBnXkFtZTcwMTkwOTY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3MzQ3NjA5N15BMl5BanBnXkFtZTcwMzY5OTY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
    ],
  },
  {
    id: 5,
    Title: "The Wolf of Wall Street",
    Year: "2013",
    Rated: "R",
    Released: "25 Dec 2013",
    Runtime: "180 min",
    Genre: "Biography, Comedy, Crime",
    Director: "Martin Scorsese",
    Writer: "Terence Winter (screenplay), Jordan Belfort (book)",
    Actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
    Plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    Language: "English, French",
    Country: "USA",
    Awards: "Nominated for 5 Oscars. Another 35 wins & 154 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/i1oHi4mPYkrAS99rzVdoiX1s1XQ.jpg",
    Metascore: "75",
    imdbRating: "8.2",
    imdbVotes: "786,985",
    imdbID: "tt0993846",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDIwMDIxNzk3Ml5BMl5BanBnXkFtZTgwMTg0MzQ4MDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0NzAxODAyMl5BMl5BanBnXkFtZTgwMDg0MzQ4MDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTExMDk1MDE4NzVeQTJeQWpwZ15BbWU4MDM4NDM0ODAx._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg3MTY4NDk4Nl5BMl5BanBnXkFtZTgwNjc0MzQ4MDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgzMTg4MDI0Ml5BMl5BanBnXkFtZTgwOTY0MzQ4MDE@._V1_SY1000_CR0,0,1553,1000_AL_.jpg",
    ],
  },
  {
    id: 6,
    Title: "Interstellar",
    Year: "2014",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Runtime: "169 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow",
    Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    Language: "English",
    Country: "USA, UK",
    Awards: "Won 1 Oscar. Another 39 wins & 134 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    Metascore: "74",
    imdbRating: "8.6",
    imdbVotes: "937,412",
    imdbID: "tt0816692",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NTEwOTMxMV5BMl5BanBnXkFtZTgwMjMyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMzQ5ODE2MzEwM15BMl5BanBnXkFtZTgwMTMyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg4Njk4MzY0Nl5BMl5BanBnXkFtZTgwMzIyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMzE3MTM0MTc3Ml5BMl5BanBnXkFtZTgwMDIyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNjYzNjE2NDk3N15BMl5BanBnXkFtZTgwNzEyODgxMzE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    id: 7,
    Title: "Game of Thrones",
    Year: "2011–",
    Rated: "TV-MA",
    Released: "17 Apr 2011",
    Runtime: "56 min",
    Genre: "Adventure, Drama, Fantasy",
    Director: "N/A",
    Writer: "David Benioff, D.B. Weiss",
    Actors: "Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington",
    Plot: "While a civil war brews between several noble families in Westeros, the children of the former rulers of the land attempt to rise up to power. Meanwhile a forgotten race, bent on destruction, plans to return after thousands of years in the North.",
    Language: "English",
    Country: "USA, UK",
    Awards: "Won 1 Golden Globe. Another 185 wins & 334 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "1,046,830",
    imdbID: "tt0944947",
    Type: "series",
    totalSeasons: "7",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDc1MGUyNzItNWRkOC00MjM1LWJjNjMtZTZlYWIxMGRmYzVlXkEyXkFqcGdeQXVyMzU3MDEyNjk@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BZjZkN2M5ODgtMjQ2OC00ZjAxLWE1MjMtZDE0OTNmNGM0NWEwXkEyXkFqcGdeQXVyNjUxNzgwNTE@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMDk4Y2Y1MDAtNGVmMC00ZTlhLTlmMmQtYjcyN2VkNzUzZjg2XkEyXkFqcGdeQXVyNjUxNzgwNTE@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNjZjNWIzMzQtZWZjYy00ZTkwLWJiMTYtOWRkZDBhNWJhY2JmXkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNTMyMTRjZWEtM2UxMS00ZjU5LWIxMTYtZDA5YmJhZmRjYTc4XkEyXkFqcGdeQXVyMjk3NTUyOTc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
    ],
  },
  {
    id: 8,
    Title: "Vikings",
    Year: "2013–",
    Rated: "TV-14",
    Released: "03 Mar 2013",
    Runtime: "44 min",
    Genre: "Action, Drama, History",
    Director: "N/A",
    Writer: "Michael Hirst",
    Actors: "Travis Fimmel, Clive Standen, Gustaf Skarsgård, Katheryn Winnick",
    Plot: "The world of the Vikings is brought to life through the journey of Ragnar Lothbrok, the first Viking to emerge from Norse legend and onto the pages of history - a man on the edge of myth.",
    Language: "English, Old English, Norse, Old, Latin",
    Country: "Ireland, Canada",
    Awards:
      "Nominated for 7 Primetime Emmys. Another 17 wins & 49 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    Metascore: "N/A",
    imdbRating: "8.6",
    imdbVotes: "198,041",
    imdbID: "tt2306299",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM5MTM1ODUxNV5BMl5BanBnXkFtZTgwNTAzOTI2ODE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNzU2NDcxODMyOF5BMl5BanBnXkFtZTgwNDAzOTI2ODE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMzMzIzOTU2M15BMl5BanBnXkFtZTgwODMzMTkyODE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NTQ2MDA3NF5BMl5BanBnXkFtZTgwODkxMDUxODE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcxOTQ3NTA5N15BMl5BanBnXkFtZTgwMzExMDUxODE@._V1_SY1000_SX1500_AL_.jpg",
    ],
  },
  {
    id: 9,
    Title: "Gotham",
    Year: "2014–",
    Rated: "TV-14",
    Released: "01 Aug 2014",
    Runtime: "42 min",
    Genre: "Action, Crime, Drama",
    Director: "N/A",
    Writer: "Bruno Heller",
    Actors: "Ben McKenzie, Donal Logue, David Mazouz, Sean Pertwee",
    Plot: "The story behind Detective James Gordon's rise to prominence in Gotham City in the years before Batman's arrival.",
    Language: "English",
    Country: "USA",
    Awards: "Nominated for 4 Primetime Emmys. Another 3 wins & 22 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/4XddcRDtnNjYmLRMYpbrhFxsbuq.jpg",
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "133,375",
    imdbID: "tt3749900",
    Type: "series",
    totalSeasons: "3",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDI3ODYyODY4OV5BMl5BanBnXkFtZTgwNjE5NDMwMDI@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5OTExMTIwNF5BMl5BanBnXkFtZTgwMjI5NDMwMDI@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA3MDY2NjA3MzBeQTJeQWpwZ15BbWU4MDU0MDkzODgx._V1_SX1499_CR0,0,1499,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3MzYzNDgzOV5BMl5BanBnXkFtZTgwMjQwOTM4ODE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQwODAyNjk0NF5BMl5BanBnXkFtZTgwODU4MzMyODE@._V1_SY1000_CR0,0,1500,1000_AL_.jpg",
    ],
  },
  {
    id: 10,
    Title: "Power",
    Year: "2014–",
    Rated: "TV-MA",
    Released: "N/A",
    Runtime: "50 min",
    Genre: "Crime, Drama",
    Director: "N/A",
    Writer: "Courtney Kemp Agboh",
    Actors: "Omari Hardwick, Joseph Sikora, Andy Bean, Lela Loren",
    Plot: 'James "Ghost" St. Patrick, a wealthy New York night club owner who has it all, catering for the city\'s elite and dreaming big, lives a double life as a drug kingpin.',
    Language: "English",
    Country: "USA",
    Awards: "1 win & 6 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/6sj8HFCODqHah4DTCWs8uPp4IyL.jpg",
    Metascore: "N/A",
    imdbRating: "8.0",
    imdbVotes: "14,770",
    imdbID: "tt3281796",
    Type: "series",
    totalSeasons: "3",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2ODg0MzMzM15BMl5BanBnXkFtZTgwODYxODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcyMjA0MzczNV5BMl5BanBnXkFtZTgwNTIyODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk0MTI0NzQ2NV5BMl5BanBnXkFtZTgwMDkxODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4Mzk1ODcxM15BMl5BanBnXkFtZTgwNDQyODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwNTE0NDI1M15BMl5BanBnXkFtZTgwMDQyODA5NTE@._V1_SY1000_SX1500_AL_.jpg",
    ],
  },
  {
    id: 11,
    Title: "Narcos",
    Year: "2015–",
    Rated: "TV-MA",
    Released: "28 Aug 2015",
    Runtime: "49 min",
    Genre: "Biography, Crime, Drama",
    Director: "N/A",
    Writer: "Carlo Bernard, Chris Brancato, Doug Miro, Paul Eckstein",
    Actors: "Wagner Moura, Boyd Holbrook, Pedro Pascal, Joanna Christie",
    Plot: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "Nominated for 2 Golden Globes. Another 4 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/w220_and_h330_face/rTmal9fDbwh5F0waol2hq35U4ah.jpg",
    Metascore: "N/A",
    imdbRating: "8.9",
    imdbVotes: "118,680",
    imdbID: "tt2707408",
    Type: "series",
    totalSeasons: "2",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2MDMzMTc0MF5BMl5BanBnXkFtZTgwMTAyMzA1OTE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxMDkyOTEyNV5BMl5BanBnXkFtZTgwNjY3Mjc3OTE@._V1_SY1000_SX1500_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA2NDUwMTU2NV5BMl5BanBnXkFtZTgwNTI1Mzc3OTE@._V1_SY1000_CR0,0,1499,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BODA1NjAyMTQ3Ml5BMl5BanBnXkFtZTgwNjI1Mzc3OTE@._V1_SY1000_CR0,0,1499,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU0NzQ0OTAwNl5BMl5BanBnXkFtZTgwMDAyMzA1OTE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    id: 12,
    Title: "Breaking Bad",
    Year: "2008–2013",
    Rated: "TV-14",
    Released: "20 Jan 2008",
    Runtime: "49 min",
    Genre: "Crime, Drama, Thriller",
    Director: "N/A",
    Writer: "Vince Gilligan",
    Actors: "Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris",
    Plot: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's financial future.",
    Language: "English, Spanish",
    Country: "USA",
    Awards: "Won 2 Golden Globes. Another 132 wins & 218 nominations.",
    Poster:
      "https://www.themoviedb.org/t/p/original/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "889,883",
    imdbID: "tt0903747",
    Type: "series",
    totalSeasons: "5",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgyMzI5NDc5Nl5BMl5BanBnXkFtZTgwMjM0MTI2MDE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ2NDkwNDk5NV5BMl5BanBnXkFtZTgwNDM0MTI2MDE@._V1_SY1000_CR0,0,1495,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM4NDcyNDMzMF5BMl5BanBnXkFtZTgwOTI0MTI2MDE@._V1_SY1000_CR0,0,1495,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTAzMTczMjM3NjFeQTJeQWpwZ15BbWU4MDc1MTI1MzAx._V1_SY1000_CR0,0,1495,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5MTE3MTgwMF5BMl5BanBnXkFtZTgwOTQxMjUzMDE@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
    ],
  },
  {
    id: 13,
    ComingSoon: true,
    Title: "Doctor Strange",
    Year: "2016",
    Rated: "N/A",
    Released: "04 Nov 2016",
    Runtime: "N/A",
    Genre: "Action, Adventure, Fantasy",
    Director: "Scott Derrickson",
    Writer:
      "Scott Derrickson (screenplay), C. Robert Cargill (screenplay), Jon Spaihts (story by), Scott Derrickson (story by), C. Robert Cargill (story by), Steve Ditko (comic book)",
    Actors:
      "Rachel McAdams, Benedict Cumberbatch, Mads Mikkelsen, Tilda Swinton",
    Plot: "After his career is destroyed, a brilliant but arrogant and conceited surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/original/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt1211837",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3ODc1ODI5Ml5BMl5BanBnXkFtZTgwODMzMDY3OTE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgxNTAyNTU0NV5BMl5BanBnXkFtZTgwNzMzMDY3OTE@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5NDc5NzUwNV5BMl5BanBnXkFtZTgwMDM3MDM2NzE@._V1_.jpg",
    ],
  },
  {
    id: 14,
    ComingSoon: true,
    Title: "Rogue One: A Star Wars Story",
    Year: "2016",
    Rated: "N/A",
    Released: "16 Dec 2016",
    Runtime: "N/A",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Gareth Edwards",
    Writer:
      "Chris Weitz (screenplay), Tony Gilroy (screenplay), John Knoll (story), Gary Whitta (story), George Lucas (characters)",
    Actors: "Felicity Jones, Riz Ahmed, Mads Mikkelsen, Ben Mendelsohn",
    Plot: "The Rebellion makes a risky move to steal the plans to the Death Star, setting up the epic saga to follow.",
    Language: "English",
    Country: "USA",
    Awards: "1 nomination.",
    Poster:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjQyMzI2OTA3OF5BMl5BanBnXkFtZTgwNDg5NjQ0OTE@._V1_SY1000_CR0,0,674,1000_AL_.jpg",
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt3748528",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE3MzA4Nzk3NV5BMl5BanBnXkFtZTgwNjAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNDMxMTQzMjQxM15BMl5BanBnXkFtZTgwNzAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUyNjkxOTk5NV5BMl5BanBnXkFtZTgwODAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BNjM4MzExNDAyNl5BMl5BanBnXkFtZTgwOTAxMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE3NTgxMDcyNV5BMl5BanBnXkFtZTgwMDExMTc1ODE@._V1_SX1777_CR0,0,1777,744_AL_.jpg",
    ],
  },
  {
    id: 15,
    ComingSoon: true,
    Title: "Assassin's Creed",
    Year: "2016",
    Rated: "N/A",
    Released: "21 Dec 2016",
    Runtime: "N/A",
    Genre: "Action, Adventure, Fantasy",
    Director: "Justin Kurzel",
    Writer:
      "Bill Collage (screenplay), Adam Cooper (screenplay), Michael Lesslie (screenplay)",
    Actors:
      "Michael Fassbender, Michael Kenneth Williams, Marion Cotillard, Jeremy Irons",
    Plot: "When Callum Lynch explores the memories of his ancestor Aguilar and gains the skills of a Master Assassin, he discovers he is a descendant of the secret Assassins society.",
    Language: "English",
    Country: "UK, France, USA, Hong Kong",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/original/ne5LmY2zq2dTG8TDGJOrCB4IbRy.jpg",
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt2094766",
    Type: "movie",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BN2EyYzgyOWEtNTY2NS00NjRjLWJiNDYtMWViMjg5MWZjYjgzXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwOWYzOTctOTc4My00ZmJkLTgzMTctMmUxNDI5ODQzYzNjXkEyXkFqcGdeQXVyNDAyODU1Njc@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BZTY5ZGUxMTAtYTU0OC00NGQ2LTkzNzgtZGZmNjlmNjY3MGU0XkEyXkFqcGdeQXVyNTY0MTkxMTg@._V1_SY1000_CR0,0,1500,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BZjA0MWYwZTEtYzc5Yi00NGM2LTg1YTctNjY2YzQ0NDJhZDAwXkEyXkFqcGdeQXVyNDAyODU1Njc@._V1_SY1000_CR0,0,1499,1000_AL_.jpg",
    ],
  },
  {
    id: 16,
    ComingSoon: true,
    Title: "Luke Cage",
    Year: "2016–",
    Rated: "TV-MA",
    Released: "30 Sep 2016",
    Runtime: "55 min",
    Genre: "Action, Crime, Drama",
    Director: "N/A",
    Writer: "Cheo Hodari Coker",
    Actors: "Mahershala Ali, Mike Colter, Frankie Faison, Erik LaRay Harvey",
    Plot: "Given superstrength and durability by a sabotaged experiment, a wrongly accused man escapes prison to become a superhero for hire.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://www.themoviedb.org/t/p/original/quTfV803fGaSADzTeEqCbIZnt9d.jpg",
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt3322314",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
    Images: [
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMxNjc1NjI0NV5BMl5BanBnXkFtZTgwNzA0NzY0ODE@._V1_SY1000_CR0,0,1497,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1MDg3NjY2OF5BMl5BanBnXkFtZTgwNDE1NDU4OTE@._V1_SY1000_CR0,0,1497,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BOTYzOTQyNDYxNl5BMl5BanBnXkFtZTgwNzA1NDU4OTE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgxMjA3MTQ5Ml5BMl5BanBnXkFtZTgwOTA1NDU4OTE@._V1_SY1000_CR0,0,1498,1000_AL_.jpg",
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMyNjg5ODYwNF5BMl5BanBnXkFtZTgwMTE1NDU4OTE@._V1_SY1000_CR0,0,1477,1000_AL_.jpg",
    ],
  },
  // data that isn't complete
  {
    id: 17,
    ComingSoon: true,
    Title: "Ms. Marvel",
    Year: "2022",
    Rated: "NR",
    Released: null,
    Runtime: null,
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "A great student, avid gamer, and voracious fan-fic scribe, Kamala Khan has a special affinity for Super Heroes, particularly Captain Marvel. However, she struggles to fit in at home and at school — that is, until she gets super powers like the heroes she’s always looked up to. Life is easier with super powers, right?",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/xN4jAr5Tz640oZYxrDMlpolt5cY.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/reG6Pk1ABZEYssn8ZKzUC2VHJkT.jpg",
      "https://www.themoviedb.org/t/p/original/d7Id9xnYNGAXl84Nt4WiYfcF4zj.jpg",
      "https://thecinemaholic.com/wp-content/uploads/2019/09/MsMarvel36.0.jpg",
      "https://imgs.search.brave.com/Auy34zEcE1dJi4kyZ_4xRdpfZpkLGW3LymXfh0BDbDI/rs:fit:1200:700:1/g:ce/aHR0cHM6Ly9zdGF0/aWMxLmNvbGxpZGVy/aW1hZ2VzLmNvbS93/b3JkcHJlc3Mvd3At/Y29udGVudC91cGxv/YWRzLzIwMjAvMTIv/bXMtbWFydmVsLWRp/c25leS1wbHVzLXNv/Y2lhbC5qcGc",
      "https://buzzquad.com/wp-content/uploads/2020/12/Ms-Marvel-Trailer-First-Look-Disney-Plus-760x456.jpg",
    ],
  },
  {
    id: 18,
    ComingSoon: true,
    Title: "The Bad Guys",
    Year: "2022",
    Rated: "PG",
    Released: null,
    Runtime: null,
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/9IDJpHROaC0S1ZlIxrvzOcOX5yC.jpg",
      "https://www.themoviedb.org/t/p/original/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
      "https://www.themoviedb.org/t/p/original/ea3nuV8XgPe5HOrQec1uzX1mzdY.jpg",
    ],
  },
  {
    id: 19,
    ComingSoon: true,
    Title: "Doctor Strange in the Mulitverse of Madness",
    Year: "2022",
    Rated: "PG-13",
    Released: null,
    Runtime: null,
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/w440_and_h660_face/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg",
      "https://www.themoviedb.org/t/p/original/zUYGHXnIVkP7HHipLm1P0jhwIbJ.jpg",
      "https://www.themoviedb.org/t/p/original/11ZcwW7KqNPwKzFcyFGrA0MBt49.jpg",
    ],
  },
  {
    id: 20,
    ComingSoon: true,
    Title: "Fantastic Beasts: The Secrets of Dumbledore",
    Year: "2022",
    Rated: "PG-13",
    Released: "04/15/2022",
    Runtime: "2h 22m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
      "https://www.themoviedb.org/t/p/original/wdjdHBDwmynWUrJcNzS24uegvK5.jpg",
      "https://www.themoviedb.org/t/p/original/uq54wVdwv3D91h99yZZCPK7OSKJ.jpg",
    ],
  },
  {
    id: 21,
    ComingSoon: true,
    Title: "Encanto",
    Year: "2021",
    Rated: "PG",
    Released: "11/24/2021",
    Runtime: "1h 42m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
      "https://www.themoviedb.org/t/p/original/2hZd9enh7Fhyrw8Fw08T7EDtin9.jpg",
      "https://www.themoviedb.org/t/p/original/2Sm3asuwKVNTzgm2nF6hp5mwEfh.jpg",
    ],
  },
  {
    id: 22,
    ComingSoon: true,
    Title: "Marvel's Daredevil",
    Year: "2015",
    Rated: "TV-MA",
    Released: null,
    Runtime: "52 m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Lawyer-by-day Matt Murdock uses his heightened senses from being blinded as a young boy to fight crime at night on the streets of Hell’s Kitchen as Daredevil.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/2qfaHJaodEbMmj9GXMvj84mbpy3.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/d9XCFoSYbnz4et3TRoxlI1e7ozh.jpg",
      "https://www.themoviedb.org/t/p/original/qsnXwGS7KBbX4JLqHvICngtR8qg.jpg",
      "https://www.themoviedb.org/t/p/original/jy8zlPPD3LQZa2Cq41iRg6IXD7u.jpg",
    ],
  },
  {
    id: 23,
    ComingSoon: true,
    Title: "Marvel's Inhumans",
    Year: "2017",
    Rated: "TV-PG",
    Released: null,
    Runtime: "43m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/zKfGip55oJ9tdzhyd9ayGyFFhuo.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/9GNdPoCSzWYeo2eYKFVLvzcG6Wg.jpg",
      "https://www.themoviedb.org/t/p/original/34Aezq9pCURMaunM8NtDF3EdvJn.jpg",
      "https://www.themoviedb.org/t/p/original/s8Fuj8EkOQcP28sKsSWpwTBJ2EJ.jpg",
    ],
  },
  {
    id: 24,
    ComingSoon: true,
    Title: "Pil's Adventures",
    Year: "2021",
    Rated: "PG",
    Released: "08/11/2021",
    Runtime: "1h 29m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Pil, a little vagabond girl, lives on the streets of the medieval city of Roc-en-Brume, along with her three tame weasels. She survives of food stolen from the castle of the sinister Regent Tristain. One day, to escape his guards, Pil disguises herself as a princess. Thus she embarks upon a mad, delirious adventure, together with Crobar, a big clumsy guard who thinks she's a noble, and Rigolin, a young crackpot jester. Pil is going to have to save Roland, rightful heir to the throne under the curse of a spell. This adventure will turn the entire kingdom upside down, and teach Pil that nobility can be found in all of us.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/abPQVYyNfVuGoFUfGVhlNecu0QG.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/vOwYumTlCZCRRzquAanPQUzfZIk.jpg",
      "https://www.themoviedb.org/t/p/original/aHxKWnkqFb6CLUnfPBPOhtykQov.jpg",
      "https://www.themoviedb.org/t/p/original/tq3klWQevRK0Or0cGhsw0h3FDWQ.jpg",
    ],
  },
  {
    id: 25,
    ComingSoon: true,
    Title: "The Matrix Resurrections",
    Year: "2021",
    Rated: "R",
    Released: "12/22/2021",
    Runtime: "2h 28m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/dB0CxRwLXJoOrRPUvsJjb2hnPtq.jpg",
      "https://www.themoviedb.org/t/p/original/ilHolgnOBj9edLGVFlbaqcaexgL.jpg",
      "https://www.themoviedb.org/t/p/original/k0Cuybu9ECuc47ODlHcIP8TJCZi.jpg",
    ],
  },
  {
    id: 26,
    ComingSoon: true,
    Title: "Looop Lapeta",
    Year: "2022",
    Rated: "R",
    Released: "02/04/2022",
    Runtime: "2h 11m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "When her boyfriend loses a mobster's cash, Savi races against the clock to save the day — if only she can break out of a curious cycle of dead ends.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/onGdT8sYi89drvSJyEJnft97rOq.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/kQM7o3NIkruIZLoQ9E2XzZQ8Ujl.jpg",
      "https://www.themoviedb.org/t/p/original/mzEVoxbMsk41bjxZaDwGXX2nTSZ.jpg",
      "https://www.themoviedb.org/t/p/original/2IxpI2VRfsaD6VMI3zIHIcu8R9G.jpg",
    ],
  },
  {
    id: 27,
    ComingSoon: true,
    Title: "Doctor Strange",
    Year: "2007",
    Rated: "PG-13",
    Released: "18/14/2007",
    Runtime: "1h 16m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Dr. Stephen Strange embarks on a wondrous journey to the heights of a Tibetan mountain, where he seeks healing at the feet of the mysterious Ancient One.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/kP5ihakYGSTZ7FQDXBSbqla9men.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/vy3uI3PCQWVnoW7OrKzB65Ba02c.jpg",
      "https://www.themoviedb.org/t/p/original/mQ30ClWsTO8QBTkbwArIifkRlhZ.jpg",
      "https://www.themoviedb.org/t/p/original/pSKwKVLLzG5VCV2kqATkBQEJmQQ.jpg",
    ],
  },
  {
    id: 28,
    ComingSoon: true,
    Title: "Chernobyl: Abyss",
    Year: "2021",
    Rated: "12+",
    Released: "04/15/2021",
    Runtime: "2h 16m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/AmJLuHjxPdIJO6vmymeWADG6jK5.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/xGrTm3J0FTafmuQ85vF7ZCw94x6.jpg",
      "https://www.themoviedb.org/t/p/original/qDqorNvx3P86LSoWOIAmJwMPdRH.jpg",
      "https://www.themoviedb.org/t/p/original/rFUB8ydD4oVhogglyOtr0YU2CHQ.jpg",
    ],
  },
  {
    id: 29,
    ComingSoon: true,
    Title: "The Weekend Away",
    Year: "2022",
    Rated: "NC16",
    Released: "03/03/2022",
    Runtime: "1h 31m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "When her best friend vanishes during a girls' trip to Croatia, Beth races to figure out what happened. But each clue yields another unsettling deception.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/6MS0QEl7UK2gdFFbHfNwuYlsq4H.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/isBUqT3hGKvzIoiGcVzURh1EdvQ.jpg",
      "https://www.themoviedb.org/t/p/original/ogBxTYI7TDSnkUONkwK4R8hM1lE.jpg",
      "https://www.themoviedb.org/t/p/original/18Aa9nCIyM5pOedRtEe3clMU4ST.jpg",
    ],
  },
  {
    id: 30,
    ComingSoon: true,
    Title: "Free Guy",
    Year: "2021",
    Rated: "PG-13",
    Released: "08/13/2021",
    Runtime: "1h 66m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
      "https://www.themoviedb.org/t/p/original/s5g9IRR8QWgwuIrxPp9wI59M7V9.jpg",
      "https://www.themoviedb.org/t/p/original/nHNchf48sNeKgBGvSX6lOddsOUH.jpg",
    ],
  },
  {
    id: 31,
    ComingSoon: true,
    Title: "Luca",
    Year: "2021",
    Rated: "PG",
    Released: "06/17/2021",
    Runtime: "1h 35m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/8tABCBpzu3mZbzMB3sRzMEHEvJi.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg",
      "https://www.themoviedb.org/t/p/original/cS9wPYC99khLSBKvmhLATAVa19x.jpg",
      "https://www.themoviedb.org/t/p/original/eqAGEN60pHPdkHTryQtmOxaM5sa.jpg",
    ],
  },
  {
    id: 32,
    ComingSoon: true,
    Title: "Ron's Gone Wrong",
    Year: "2021",
    Rated: "PG",
    Released: "10/22/2021",
    Runtime: "1h 47m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "In a world where walking, talking, digitally connected bots have become children's best friends, an 11-year-old finds that his robot buddy doesn't quite work the same as the others do.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/plzgQAXIEHm4Y92ktxU6fedUc0x.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/sdL37sfUBth7mdkAolI83bXAl7L.jpg",
      "https://www.themoviedb.org/t/p/original/99OiyEOsFecBiS5XkhQAB98rlP6.jpg",
      "https://www.themoviedb.org/t/p/original/40WhgHxqkVPJeFIGeVFF48DB5e5.jpg",
    ],
  },
  {
    id: 33,
    ComingSoon: true,
    Title: "Morbius",
    Year: "2022",
    Rated: "PG-13",
    Released: "04/01/2022",
    Runtime: "1h 44m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/h4WLN3cmEjCsH1fNGRfvGV6IPBX.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/l5gbMbZICazywW3dWsgziw988Gl.jpg",
      "https://www.themoviedb.org/t/p/original/kdUArJCSTW8bpJipOqkvCZsVEqi.jpg",
      "https://www.themoviedb.org/t/p/original/xFAbQnrV7vsW4obvqfyWoEF1YuZ.jpg",
    ],
  },
  {
    id: 34,
    ComingSoon: true,
    Title: "Shang-Chi and the Legend of the Ten Rings",
    Year: "2021",
    Rated: "PG-13",
    Released: "09/03/2021",
    Runtime: "2h 28m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/zxWAv1A34kdYslBi4ekMDtgIGUt.jpg",
      "https://www.themoviedb.org/t/p/original/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
      "https://www.themoviedb.org/t/p/original/yVE91U9wlDN3EicZdhnsc7ofJEY.jpg",
    ],
  },
  {
    id: 35,
    ComingSoon: true,
    Title: "Ghostbusters: Afterlife",
    Year: "2021",
    Rated: "PG-13",
    Released: "11/19/2021",
    Runtime: "2h 4m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
      "https://www.themoviedb.org/t/p/original/4sybNiCalJXketLuULuxtP8vz04.jpg",
      "https://www.themoviedb.org/t/p/original/l4A4AoPYfu61BS9bVoERnVRAtzj.jpg",
    ],
  },
  {
    id: 36,
    ComingSoon: true,
    Title: "Cruella",
    Year: "2021",
    Rated: "PG-13",
    Released: "05/28/2021",
    Runtime: "2h 14m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "In 1970s London amidst the punk rock revolution, a young grifter named Estella is determined to make a name for herself with her designs. She befriends a pair of young thieves who appreciate her appetite for mischief, and together they are able to build a life for themselves on the London streets. One day, Estella’s flair for fashion catches the eye of the Baroness von Hellman, a fashion legend who is devastatingly chic and terrifyingly haute. But their relationship sets in motion a course of events and revelations that will cause Estella to embrace her wicked side and become the raucous, fashionable and revenge-bent Cruella.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/wToO8opxkGwKgSfJ1JK8tGvkG6U.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/sgHmoqF97bjM1HUyw43FzjzXtEr.jpg",
      "https://www.themoviedb.org/t/p/original/5tZkPgnRIT0sRYzMDyzYZx5ZFrZ.jpg",
      "https://www.themoviedb.org/t/p/original/8ChCpCYxh9YXusmHwcE9YzP0TSG.jpg",
    ],
  },
  {
    id: 37,
    ComingSoon: true,
    Title: "Dune",
    Year: "2021",
    Rated: "PG-13",
    Released: "10/22/2021",
    Runtime: "2h 35m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
      "https://www.themoviedb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
      "https://www.themoviedb.org/t/p/original/tHRo2pQDnbHCKsL3KABEnJX9ioz.jpg",
    ],
  },
  {
    id: 38,
    ComingSoon: true,
    Title: "Space Jam: A New Legacy",
    Year: "2021",
    Rated: "PG",
    Released: "07/16/2021",
    Runtime: "1h 55m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/bKHNh16zIp0PN44LrgP7PwKy2PH.jpg",
      "https://www.themoviedb.org/t/p/original/8s4h9friP6Ci3adRGahHARVd76E.jpg",
      "https://www.themoviedb.org/t/p/original/pQh0mtqhIAh6Redv505ncWJjNpU.jpg",
    ],
  },
  {
    id: 39,
    ComingSoon: true,
    Title: "The Amazing Spider-Man",
    Year: "2012",
    Rated: "PG-13",
    Released: "07/03/2012",
    Runtime: "2h 16m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/sLWUtbrpiLp23a0XDSiUiltdFPJ.jpg",
      "https://www.themoviedb.org/t/p/original/bShd9jt4LAg6LzSJqBZMW99vh4k.jpg",
      "https://www.themoviedb.org/t/p/original/ysZsHNE8AxgfvrpidICaDTRGTwe.jpg",
    ],
  },
  {
    id: 40,
    ComingSoon: true,
    Title: "Infinite",
    Year: "2021",
    Rated: "PG-13",
    Released: "09/09/2021",
    Runtime: "1h 46m",
    Genre: null,
    Director: null,
    Writer: null,
    Actors: null,
    Plot: "van McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
    Language: "English",
    Country: "USA",
    Awards: null,
    Poster:
      "https://www.themoviedb.org/t/p/original/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
    Metascore: null,
    imdbRating: null,
    imdbVotes: null,
    imdbID: null,
    Type: null,
    totalSeasons: null,
    Response: null,
    Images: [
      "https://www.themoviedb.org/t/p/original/h9dDR4RivmaqLacAMhkm8CoizQT.jpg",
      "https://www.themoviedb.org/t/p/original/oYmZ9MGKeIVRxVaIGggVdR6revI.jpg",
      "https://www.themoviedb.org/t/p/original/bWCqVYJogdEMSXh4tj7WFqR0cpY.jpg",
    ],
  },
];

module.exports = { Movies2 };
